services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pingpong-postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pingpong
    ports:
      - "5432:5432"
    volumes:
      - ping-pong-data-sql:/var/lib/postgresql

volumes:
  ping-pong-data-sql: