apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/postgres-db.yaml
- manifests/ping-pong-service.yaml
- manifests/ping-pong-deployment.yaml
- manifests/log-output-configmap.yaml
- manifests/log-output-service.yaml
- manifests/log-output-deployment.yaml
- manifests/ping-pong-route.yaml
- manifests/log-output-route.yaml
- manifests/gateway.yaml
images:
- name: log-output
  newName: adamfarhadi/dwk-log-output
  newTag: 97603d7bb1ee2978b24798a2ab3d3e2981152aeb
- name: ping-pong
  newName: adamfarhadi/dwk-ping-pong
  newTag: 97603d7bb1ee2978b24798a2ab3d3e2981152aeb
