apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/postgres-db.yaml
  - manifests/ping-pong-service.yaml
  # - manifests/ping-pong-deployment.yaml
  - manifests/ping-pong-analysis-template.yaml
  - manifests/ping-pong-rollout.yaml
  - manifests/log-output-configmap.yaml
  - manifests/log-output-service.yaml
  - manifests/log-output-deployment.yaml
  - manifests/ping-pong-route.yaml
  - manifests/log-output-route.yaml
  - manifests/gateway.yaml