apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/postgres-db.yaml
- manifests/ping-pong-service.yaml
- manifests/ping-pong-deployment.yaml
- manifests/log-output-configmap.yaml
- manifests/log-output-service.yaml
- manifests/log-output-deployment.yaml
- manifests/ping-pong-route.yaml
- manifests/log-output-route.yaml
- manifests/gateway.yaml
images:
- name: log-output
  newName: adamfarhadi/dwk-log-output
  newTag: ed9f7b417b1245c8e9f26ed8fb3cfc07baf4d71c
- name: ping-pong
  newName: adamfarhadi/dwk-ping-pong
  newTag: ed9f7b417b1245c8e9f26ed8fb3cfc07baf4d71c
