apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: log-output
          image: adamfarhadi/dwk-log-output:2.1
          imagePullPolicy: Always
          env:
          - name: PORT
            value: "3001"
          - name: MESSAGE
            valueFrom:
              configMapKeyRef:
                name: log-output-cm
                key: MESSAGE
          volumeMounts:
          - name: information-volume
            mountPath: "/etc/information"
            readOnly: true
      volumes:
      - name: information-volume
        configMap:
          name: log-output-cm
          items: 
          - key: information.txt
            path: information.txt