apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: ping-pong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: adamfarhadi/dwk-ping-pong:2.5
          imagePullPolicy: Always
          env:
          - name: PORT
            value: "3001"
          - name: DATABASE_URL
            value: "postgres://postgres:postgres@postgres-svc/pingpong"
          volumeMounts: 
          - name: postgres-pingpong-initdb
            mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: postgres-pingpong-initdb
          configMap:
            name: postgres-pingpong-initdb-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-pingpong-initdb-config
data:
  seed.sql: |
    CREATE TABLE counter (
    id BOOLEAN PRIMARY KEY DEFAULT TRUE,
    value INTEGER NOT NULL DEFAULT 0
    );
    INSERT INTO counter (value) VALUES (0);