apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: project
  name: todo-app-claim
spec:
  storageClassName: my-todo-app-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi