apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: project
  name: todo-app-claim # name of the volume claim, this will be used in the deployment
spec:
  storageClassName: my-todo-app-pv # this is the name of the persistent volume we are claiming
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi