apiVersion: v1
kind: Service
metadata:
  namespace: project
  name: todo-app-backend-svc
spec:
  type: NodePort
  selector:
    app: todo-app-backend
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000