apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: project
  name: todo-app-random-wiki-cronjob
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: todo-app-random-wiki-cronjob
            image: adamfarhadi/dwk-todo-app-random-wiki-cronjob:3.5
            imagePullPolicy: Always
            command:
            - /usr/local/bin/random-wiki.sh
          restartPolicy: OnFailure
