apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-app-random-wiki-cronjob
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: todo-app-random-wiki
            image: todo-app-random-wiki
            imagePullPolicy: Always
            command:
            - /usr/local/bin/random-wiki.sh
          restartPolicy: OnFailure