apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/todo-app-postgres-db.yaml
  - manifests/todo-app-backend-service.yaml
  - manifests/todo-app-backend-deployment.yaml
  - manifests/todo-app-pvc.yaml
  - manifests/todo-app-service.yaml
  - manifests/todo-app-deployment.yaml
  - manifests/ingress.yaml
  - manifests/todo-app-random-wiki-cronjob.yaml