services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-app-postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo-app
    ports:
      - "5432:5432"
    volumes:
      - todo-app-data-sql:/var/lib/postgresql

volumes:
  todo-app-data-sql: