name: Build and publish todo app

on:
  push:
    branches:
      - main
    paths:
      - 'todo-app/**'
  workflow_dispatch:
    
env:
  DOCKER_HUB_USERNAME: adamfarhadi
  TODO_APP_IMAGE: dwk-todo-app
  TODO_APP_BACKEND_IMAGE: dwk-todo-app-backend
  TODO_APP_RANDOM_WIKI_IMAGE: dwk-todo-app-random-wiki

jobs:
  build-publish:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest
    environment:
      name: todo-app-prod

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name : 'Form todo-app image name'
        run: |
          echo "TODO_APP_IMAGE_TAG=$DOCKER_HUB_USERNAME/$TODO_APP_IMAGE:$GITHUB_SHA" >> $GITHUB_ENV
          echo "TODO_APP_IMAGE_LATEST_TAG=$DOCKER_HUB_USERNAME/$TODO_APP_IMAGE:latest" >> $GITHUB_ENV

      - name : 'Form todo-app-backend image name'
        run: |
          echo "TODO_APP_BACKEND_IMAGE_TAG=$DOCKER_HUB_USERNAME/$TODO_APP_BACKEND_IMAGE:$GITHUB_SHA" >> $GITHUB_ENV
          echo "TODO_APP_BACKEND_IMAGE_LATEST_TAG=$DOCKER_HUB_USERNAME/$TODO_APP_BACKEND_IMAGE:latest" >> $GITHUB_ENV

      - name : 'Form todo-app-random-wiki image name'
        run: |
          echo "TODO_APP_RANDOM_WIKI_IMAGE_TAG=$DOCKER_HUB_USERNAME/$TODO_APP_RANDOM_WIKI_IMAGE:$GITHUB_SHA" >> $GITHUB_ENV
          echo "TODO_APP_RANDOM_WIKI_IMAGE_LATEST_TAG=$DOCKER_HUB_USERNAME/$TODO_APP_RANDOM_WIKI_IMAGE:latest" >> $GITHUB_ENV

      - name: 'Install todo-app deps'
        run: npm ci
        working-directory: ./todo-app/todo-app

      - name: 'Install todo-app frontend deps'
        run: npm ci
        working-directory: ./todo-app/todo-app-frontend

      - name: 'Build frontend'
        run: npm run build:ui
        working-directory: ./todo-app/todo-app

      - name: Build todo-app image
        run: docker build --tag $TODO_APP_IMAGE_TAG --tag $TODO_APP_IMAGE_LATEST_TAG ./todo-app/todo-app

      - name: Publish todo-app image
        run: |
          docker push $TODO_APP_IMAGE_TAG
          docker push $TODO_APP_IMAGE_LATEST_TAG

      - name: Build todo-app-backend image
        run: docker build --tag $TODO_APP_BACKEND_IMAGE_TAG --tag $TODO_APP_BACKEND_IMAGE_LATEST_TAG ./todo-app/todo-app-backend

      - name: Publish todo-app-backend image
        run: |
          docker push $TODO_APP_BACKEND_IMAGE_TAG
          docker push $TODO_APP_BACKEND_IMAGE_LATEST_TAG

      - name: Build todo-app-random-wiki image
        run: docker build --tag $TODO_APP_RANDOM_WIKI_IMAGE_TAG --tag $TODO_APP_RANDOM_WIKI_IMAGE_LATEST_TAG ./todo-app/random-wiki

      - name: Publish todo-app-random-wiki image
        run: |
          docker push $TODO_APP_RANDOM_WIKI_IMAGE_TAG
          docker push $TODO_APP_RANDOM_WIKI_IMAGE_LATEST_TAG

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2.1.0

      - name: Deploy todo-app and todo-app-backend
        working-directory: ./todo-app
        run: |-
          kustomize edit set image todo-app=$TODO_APP_IMAGE_TAG
          kustomize edit set image todo-app-backend=$TODO_APP_BACKEND_IMAGE_TAG
          kustomize edit set image todo-app-random-wiki=$TODO_APP_RANDOM_WIKI_IMAGE_TAG

      - name: commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: 'kustomization.yaml'
          message: New version released ${{ github.sha }}
