name: Delete todo-app environment

on:
  delete:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north2-b
  BRANCH: ${{ github.event.ref }}

jobs:
  delete-namespace:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    environment:
      name: todo-app-prod

    steps:
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2

      - name: 'Get GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          project_id: '${{ env.PROJECT_ID }}'
          location: '${{ env.GKE_ZONE }}'

      - name: Delete namespace for deleted branch
        run: |-
          BRANCH_NAME="$BRANCH"
          if [ "$BRANCH_NAME" = "main" ]; then
            NAMESPACE="project"
          else
            NAMESPACE="$BRANCH_NAME"
          fi
          echo "Deleting namespace $NAMESPACE created for branch $BRANCH_NAME"
          kubectl delete namespace "$NAMESPACE" --ignore-not-found
